### PR TITLE
Fix "minLength" option to autocomplete on first character.

### PR DESCRIPTION
**Pull request by SegFault0x0**
Pull request to address #158.

### CODE REVIEW

**Comment by jlengrand** [comment]
@SegFault0x0 Great !

There's a lot of weird changes if you check the PR though. Looks like you don't handle spacing the smae way as the repo does. That amesky our changes very difficult to spot.

**Comment by SegFault0x0** [comment]
Yeah, that was Sublime's doing.  I normally try not to alter anyone else's formatting and initially tried to revert it but thought, 'The less whitespace, the better.'  I guess it'd be easier to decipher if I separated them into two different commits: one for the spacing, the other for the fix.  What do you think?  This is my first PR, so I'm up for learning the conventional standard.

**Comment by jlengrand** [comment]
Hey!

No worries, you've made a PR it's already awesome.

I'd agree with you saying that less spaces is probably a good thing. 
But a PR is meant to be as small as possible so that it can be read ad understood nicely. 

Ideally you could update this PR so that the space changes aren't there any more. You could create another PR indeed for the spacing fixes. Though I don't know what conventions the owner of the library prefers. 

Cheers!

**Comment by jlengrand** [comment]
I've just been trying, but reading the PR like this is very difficult :). Especially since I don't really know the codebase.

**Comment by SegFault0x0** [comment]
I've overwritten the initial commit to match the formatting and now it's as you would expect.  Thanks for your input!

**Comment by jlengrand** [comment]
Ha, it looks much better! Congrats for all the efforts. I'll look at it but it would also be great to have some kind of reaction from the owner of the project :).

**Pull request closed without merging**
