### PR TITLE
Allow non lat long features

### PR DESCRIPTION
**Pull request by nikolai-b**
This allows showLocation to be called with LatLon
and additionally features that respond to getBounds

### CODE REVIEW

**Comment by stefanocudini** [comment]
It's bit wrong... you can use *formatData* option!
for example here:
https://github.com/stefanocudini/leaflet-search/blob/master/examples/jsonp-filtered.html#L63
replace:
```javascript
loc = L.latLng(...
```
with:
```javascript
loc = rawjson[i].getBounds().getCenter()
```

**Comment by nikolai-b** [comment]
If I search for a city or a road it would be much nicer to zoom to the size of the feature instead of a generic zoom.  Would you reconsider or add options allow each lat log to have a zoom (not sure how...)?

**Comment by stefanocudini** [comment]
using *formatData* you can append any properties to the Loc object but now only a panto o setview is allowed.

Now only can doing this:
https://github.com/maydemirx/leaflet-search/blob/d9875ac8e0a3d0a1f0dd51d9e40611f66d101d36/src/leaflet-search.js#L794
**...this._map.panTo(latlng);...**

mmmmh interesting.. could be a good idea add new option to best define the behavior when result is found.


I'll think about this

**Comment by stefanocudini** [comment]
replace option zoom with noew callback option:
https://github.com/stefanocudini/leaflet-search/blob/master/src/leaflet-search.js#L28

demo here: 
http://labs.easyblog.it/maps/leaflet-search/examples/geojson-layer.html

**Comment by nikolai-b** [comment]
Thanks for the very fast response!

So I have a feature that I'd like to pan and zoom to.  If I can only store the feature as a `LatLng` then although your new method is helpful I've lost the zoom information.

I'd need somewhere else to store the zoom level.  To check are you suggesting something like in `formatData` having
```js
var json = {};
var feature, key;
this.options.zoom = {};
for(feature in rawjson.features){
  key = feature.properties.name;

   // store the zoom
  this.options.zoom[key] =  this.map.getBoundsZoom(feature.getBounds(), true); 

  loc = feature.getBounds().getCenter();
  json[ key ]= loc;
}
return json;
```

and then I could access the zoom in your new function:
```js
moveToLocation = function(latlng, title, map) {
  this._map.setView(latlng, this.options.zoom[title]); // access the zoom
}
```

**Comment by stefanocudini** [comment]
yes but... 
Don't needed the zoom when you know the bounds...
look here please, I use only fitBounds() method:
https://github.com/stefanocudini/leaflet-search/blob/master/examples/geojson-layer.html#L50

**Comment by stefanocudini** [comment]
for oyur code:
```javascript
moveToLocation = function(latlng, title, map) {
  var zoom = map.getBoundsZoom(latlng.layer.getBounds(), true);
  this._map.setView(latlng, zoom); // access the zoom
}
```

**Pull request closed without merging**
