### PR TITLE
Make `_recordsFromLayer` recursive, see #95

### PR DESCRIPTION
**Pull request by ghybs**
Following #95, added internal method `_searchInLayer` so that `_recordsFromLayer` can be made recursive and correctly search into nested Layer Groups of `this._layer`.

Test: http://jsfiddle.net/gevzoxs1/16/

### CODE REVIEW

**Comment by damon-rand** [comment]
Expanding on this PR... I wanted to be able to search on multiple properties of a GeoJSON Feature (for example a name, and id). I originally extended master - but this PR helps simplify things. 

Here is my code expanding this PR example http://jsfiddle.net/gevzoxs1/16/. 

In leaflet-search.src.js:
`featuresArray: [] //added to allow searching on multiple GeoJSON Properties ` added to options.

`this._featuresToSearch = this.options.featuresArray;` added to initialize.

Then use like so:
```
   // Copy-paste into your script before instantiating L.control.search.
    L.Control.Search.include({
      _searchInLayer: function(layer, retRecords, propName) {
        var that = this,
          loc;

        if (layer instanceof L.Control.Search.Marker) return;

        if (layer instanceof L.Marker || layer instanceof L.CircleMarker) {
          if (that._getPath(layer.options, propName)) {
            loc = layer.getLatLng();
            loc.layer = layer;
            retRecords[that._getPath(layer.options, propName)] = loc;
          } else if (that._getPath(layer.feature.properties, propName)) {
            loc = layer.getLatLng();
            loc.layer = layer;
            retRecords[that._getPath(layer.feature.properties, propName)] = loc;
          } else
            throw new Error("propertyName '" + propName + "' not found in marker");
        } else if (layer.hasOwnProperty('feature')) //GeoJSON
        {
          if (layer.feature.properties.hasOwnProperty(propName)) {
            loc = layer.getBounds().getCenter();
            loc.layer = layer;
            retRecords[layer.feature.properties[propName]] = loc;
          } else
            throw new Error("propertyName '" + propName + "' not found in feature");
        } else if (layer instanceof L.LayerGroup) {
          layer.eachLayer(function(layer) {
            that._searchInLayer(layer, retRecords, propName);
          });
        }
      },

      _recordsFromLayer: function() { //return table: key,value from layer
        var that = this,
          retRecords = {},
          propName = this.options.propertyName;

        if (that._featuresToSearch.length > 0) {
            this._layer.eachLayer(function(layer) {
                for (var i = 0; i < that._featuresToSearch.length; i++) {
                    that._searchInLayer(layer, retRecords, that._featuresToSearch[i]);
                }
            });
        } else {
            this._layer.eachLayer(function(layer) {
                that._searchInLayer(layer, retRecords, propName);
            });
        }
        return retRecords;
      }
    });

    var searchControl = new L.Control.Search({
        layer: layerToSearch, 
        propertyName: 'name',
        position: 'topright', 
        featuresArray: ['name', 'id'], // List of properties to search on //
        circleLocation: false
    });

    searchControl.on('search_locationfound', function (e) {
       // do stuff
    }).on('search_collapsed', function(e) {
        // do stuff
    });
    
    map.addControl(searchControl);  //initialize search control
```

**Comment by TranquilAbyss** [comment]
I would like to see this feature implemented in the main branch. I have this same problem where I am using multiple layers of vector and point layers in the same search. For now I am only having it search the point layers. Hopefully this is fixed soon.

**Comment by kaio328** [comment]
@damon-rand
this really works for me! Thank u very much!

**Comment by stefanocudini** [comment]
@ghybs solve the conflicts before send pull request tnks

**Comment by ghybs** [comment]
Hi @stefanocudini,

Thank you for your message.

Not too sure about what you mean?
IIRC, there was no conflict when I sent that PR back in Jan 2016:

image

I can certainly understand that you do not merge a PR right away, and that with time some conflicts may appear.
Unfortunately I am no longer in a position to refactor this PR.
Hopefully someone else can handle it, if its functionality is still of any value.

**Comment by stefanocudini** [comment]
Ok @ghybs ok I will try to recover this solution

**Pull request closed without merging**
