### PR TITLE
Added search for all layers in LayerGroup

### PR DESCRIPTION
**Pull request by POStroi**
Hi.
Add search for LayerGroup

```js
map = L.map(...);

// Get GeoJSON data
caffe = new L.GeoJSON.AJAX('/caffe.json', {...});
restaurant = new L.GeoJSON.AJAX(('/restaurant.json', {...});

// Add LayerGroup
city = new L.LayerGroup();
city.addLayer(caffe);
city.addLayer(restaurant);

// Add search control
map.addControl( new L.Control.Search({
       layer: city,
       propertyName:'title',
    }) );

```
:cookie:

### CODE REVIEW

**Comment by stefanocudini** [comment]
may be the best way is using same this._layer.eachLayer()  recursively inside the layergroup

**Comment by POStroi** [comment]
@stefanocudini 
Sorry, I'm not a professional in JS.
It solves the problem and it is the only thing that had the effect of

```js
city.eachLayer(function(layer){
  layer.eachLayer(function(lGroup){
          ......
  })
});
```
Not work, `layer.eachLayer(function(lGroup)...` returns an empty :(

**Comment by stefanocudini** [comment]
tnk @POStroi I'm just updated toi version 1.7.0!
and added new demo for this feature:
http://labs.easyblog.it/maps/leaflet-search/examples/multiple-layers.html

Cheers!

**Comment by POStroi** [comment]
@stefanocudini thanks for your work :+1:

**Comment by reyemtm** [comment]
I'm getting an error searching a layer group with lines and points. To make it work I changed line 536: 
```
/*loc = m.getLatLng();*/
loc = m.getBounds().getCenter();
```
Is there a reason .getLatLng is used as I see .getBounds().getCenter is used if it is not a feature group? Maybe not the best method for points?

**Comment by 360fun** [comment]
Hi! :) I'm trying to use **leaflet-search** with **layers-control** (https://leafletjs.com/examples/layers-control/) but I'm stuck: I would like to allow the search to find only activated layers (the selected ones) but I don't know what I'm doing wrong.

Following your example I added:

// adds the control layer
var layerControl = L.control.layers().addTo(map);

// adds the layer groups to the control layer
layerControl.addOverlay(caffe);
layerControl.addOverlay(restaurant);
...

// I show by default some layers in this way (the search see those even when I hide them and never see the others)
masterLayerGroup.addLayer(caffe);

How can I tell to the search work only on active layers? Should I call a "refresh" function somehow?

**Comment by stefanocudini** [comment]
layer active in layers-control is not only "activated" but they are added in the map.
leaflet-search can be search only layers added in the map.
using Leaflet layergroup for search in multiple layer
https://github.com/stefanocudini/leaflet-search/blob/master/examples/multiple-layers.html#L86

**Comment by 360fun** [comment]
I still don't understand how can I achieve it, I tried several times but "search-layer" seems not using the latest layers in the map but its the initial state! :(
Could you add "layers-control" to your example please? I think would be a nice update for everyone!
That would be great! :D

**Comment by 360fun** [comment]
For the moment I used this workaround:

var layers = {};
layers.bar = L.geoJson(bar, geojsonOpts);
layers.pharmacy = L.geoJson(pharmacy, geojsonOpts);
layers.restaurant = L.geoJson(restaurant, geojsonOpts);

layerControl.addOverlay(layers.bar, "bar");
layerControl.addOverlay(layers.pharmacy, "pharmacy");
layerControl.addOverlay(layers.restaurant, "restaurant");

// layers visible when you open the map
poiLayers.addLayer(layers.restaurant);

// function to add/remove layers from the map when overlays change
map.on('overlayadd overlayremove', function (eventLayer) {
	var layerName = eventLayer.name;

	if(eventLayer.type=='overlayadd') {
		poiLayers.addLayer(layers[layerName]);
	} else if(eventLayer.type=='overlayremove') {
		poiLayers.removeLayer(layers[layerName]);
	}
});

**Pull request merged**
