### PR TITLE
Fix broken JSONP.

### LINKED ISSUE #321: JSONP broken
Hello.

I query OSM Nominatim API via JSONP callback. Few months ago it stopped working -- whenever I try to search something,  the following error is thrown:
> Uncaught TypeError: L.Control.Search.callJsonp is not a function
 
After some investigation it turns out that recent versions call `_retrieveData` directly instead of using `this._retrieveData.call(...)`, as it was before. So instead of 2 arguments (inputText and callback) the function is called with three, so `inputText = this` and `callback = inputText`.

### PR DESCRIPTION
**Pull request by svbatalov**
Fixes #321

### CODE REVIEW

**Comment by E-gy** [comment]
Just further noting that this also fixes the exactly similar issue with Ajax mode.

**Comment by E-gy** [comment]
It seems to have broken in 3.0.9, as arguments are correct in 3.0.5 - which thus works as a temporary workaround.
image

**Comment by stefanocudini** [comment]
> It seems to have broken in 3.0.9, as arguments are correct in 3.0.5 - which thus works as a temporary workaround.

I'll check and merge soon, tnks!

**Comment by mikelcp** [comment]
@stefanocudini any updates on my pr?
It should resolve this

**Pull request merged**
